//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e5movies.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Image()
        {
            this.Reviews = new HashSet<Review>();
        }

        public int ImageID { get; set; }
        public string Title { get; set; }
        [DisplayName("Movie Poster")]
        public string ImagePath { get; set; }
        public string Genre { get; set; }
        [DisplayName("Cast")]
        public string Starring { get; set; }
        public string Director { get; set; }
        public string StoryLine { get; set; }
        [DisplayName("Release Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> DateReleased { get; set; }
        [DisplayName("Average Rating")]
        [Range(0, 10, ErrorMessage = "Rating is given from 0 to 10.")]
        public Nullable<int> RatingAVG { get; set; }
        [DisplayName("Trailer Link")]
        public string VideoPath { get; set; }
        [DisplayName("Time Uploaded")]
        public Nullable<System.DateTime> UploadTime { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
